# Generated by Django 5.1.4 on 2024-12-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=5)),
                ('code_exp', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'notification_category',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('txt', models.CharField(max_length=255)),
                ('notification_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationcategory')),
            ],
            options={
                'db_table': 'notification_template',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('role_id', models.SmallIntegerField()),
                ('active', models.SmallIntegerField(default=0, max_length=1)),
                ('verified', models.SmallIntegerField()),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='notifications.language')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=510)),
                ('address', models.CharField(max_length=510)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField(default=0)),
                ('ing', models.FloatField(default=0)),
                ('archived', models.SmallIntegerField(default=0)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.user')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.SmallIntegerField()),
                ('status', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notification_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.user')),
            ],
            options={
                'db_table': 'user_notification',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.SmallIntegerField()),
                ('txt', models.CharField(max_length=32)),
                ('user_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='notifications.usernotification')),
            ],
            options={
                'db_table': 'user_notification_option',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_notification', models.SmallIntegerField(default=0)),
                ('push_notification', models.SmallIntegerField(default=0)),
                ('notification_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.user')),
            ],
            options={
                'db_table': 'user_notification_setting',
            },
        ),
        migrations.CreateModel(
            name='TranslationString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('translation_field_id', models.IntegerField(choices=[('name', 1), ('title', 2), ('description', 3), ('text', 4), ('question', 5), ('answer', 6), ('additional', 7)], default=1)),
                ('text', models.CharField(max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notifications.language')),
            ],
            options={
                'db_table': 'translation_string',
                'unique_together': {('content_type', 'object_id', 'translation_field_id', 'language')},
            },
        ),
    ]
